apiVersion: v2
name: headlamp-platform
description: Headlamp Kubernetes management UI
type: application
version: 0.1.0
dependencies:
  - name: headlamp
    version: 0.45.0
    repository: https://kubernetes-sigs.github.io/headlamp/
