headlamp:
  replicaCount: 2

  config:
    inCluster: true
    inClusterContextName: main
    sessionTTL: 86400
    enableHelm: false
    oidc:
      secret:
        create: false

  serviceAccount:
    create: true

  clusterRoleBinding:
    create: false

  service:
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.1.1.173

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 100
    runAsGroup: 101
    seccompProfile:
      type: RuntimeDefault

  volumeMounts:
    - name: headlamp-config
      mountPath: /home/headlamp/.config

  volumes:
    - name: headlamp-config
      emptyDir:
        medium: Memory
        sizeLimit: 32Mi

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      matchLabelKeys:
        - pod-template-hash

  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  extraManifests:
    - |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: headlamp-admin
        namespace: headlamp
    - |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: headlamp-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: headlamp-admin
          namespace: headlamp
