image:
  repository: ghcr.io/gethomepage/homepage
  tag: v2.4.0

service:
  loadBalancerIP: 10.1.1.174

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 384Mi
