services:
  opencloud:
    image: opencloudeu/opencloud:7.2.4
    container_name: opencloud
    user: "1000:1000"
    entrypoint: ["/bin/sh"]
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      OC_URL: https://drive.l3b.cc.cd
      OC_LOG_LEVEL: info
      OC_LOG_COLOR: "false"
      OC_LOG_PRETTY: "false"
      PROXY_TLS: "false"
      OC_INSECURE: "false"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_CREATE_DEMO_USERS: "false"
      IDM_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
      FRONTEND_CHECK_FOR_UPDATES: "true"
      FRONTEND_ARCHIVER_MAX_SIZE: "10000000000"
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "true"
      OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "true"
      OC_PASSWORD_POLICY_MIN_CHARACTERS: "12"
      STORAGE_USERS_DRIVER: decomposeds3
      STORAGE_SYSTEM_DRIVER: decomposed
      STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: http://10.1.1.8:9000
      STORAGE_USERS_DECOMPOSEDS3_REGION: us-east-1
      STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: ${S3_ACCESS_KEY}
      STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: ${S3_SECRET_KEY}
      STORAGE_USERS_DECOMPOSEDS3_BUCKET: opencloud
      STORAGE_USERS_EVENTS_NUM_CONSUMERS: "5"
      OC_OIDC_ISSUER: https://auth.l3b.cc.cd
      PROXY_OIDC_ISSUER: https://auth.l3b.cc.cd
      OC_OIDC_CLIENT_ID: opencloud-web
      OC_OIDC_CLIENT_SCOPES: openid profile email groups
      PROXY_OIDC_CLIENT_ID: opencloud-web
      OC_EXCLUDE_RUN_SERVICES: idp
      PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
      PROXY_OIDC_REWRITE_WELLKNOWN: "true"
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      PROXY_AUTOPROVISION_CLAIM_USERNAME: preferred_username
      PROXY_AUTOPROVISION_CLAIM_EMAIL: email
      PROXY_AUTOPROVISION_CLAIM_DISPLAYNAME: name
      PROXY_AUTOPROVISION_CLAIM_GROUPS: groups
      PROXY_USER_OIDC_CLAIM: preferred_username
      PROXY_USER_CS3_CLAIM: username
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: opencloud_role
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
      GRAPH_USERNAME_MATCH: none
      SETTINGS_SETUP_DEFAULT_ASSIGNMENTS: "false"
      IDP_DOMAIN: auth.l3b.cc.cd
      WEB_OPTION_ACCOUNT_EDIT_LINK_HREF: https://auth.l3b.cc.cd
      WEB_OIDC_CLIENT_ID: opencloud-web
      WEB_OIDC_AUTHORITY: https://auth.l3b.cc.cd
      WEB_OIDC_METADATA_URL: https://auth.l3b.cc.cd/.well-known/openid-configuration
      WEB_OIDC_RESPONSE_TYPE: code
      WEB_OIDC_SCOPE: openid profile email groups
      WEBFINGER_WEB_OIDC_CLIENT_ID: opencloud-web
      WEBFINGER_WEB_OIDC_CLIENT_SCOPES: openid profile email groups
      WEBFINGER_ANDROID_OIDC_CLIENT_ID: OpenCloudAndroid
      WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES: openid profile email offline_access
      WEBFINGER_IOS_OIDC_CLIENT_ID: OpenCloudIOS
      WEBFINGER_IOS_OIDC_CLIENT_SCOPES: openid profile email offline_access
      WEBFINGER_DESKTOP_OIDC_CLIENT_ID: OpenCloudDesktop
      WEBFINGER_DESKTOP_OIDC_CLIENT_SCOPES: openid profile email offline_access
    volumes:
      - /data/apps/opencloud/config:/etc/opencloud
      - /data/apps/opencloud/data:/var/lib/opencloud
    ports:
      - 10.1.1.4:9200:9200
    networks:
      - default
      - docknet
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"
networks:
  docknet:
    external: true
