sso_providers:
- name: pocketid
  label: Pocket ID
  auto_create_users: false
  provider:
    type: custom
    client_id: warpgate
    client_secret: REPLACE_FROM_HOMELAB_WARPGATE_VAULT
    issuer_url: https://auth.l3b.cc.cd
    scopes:
    - email
    - profile
external_host: remote.l3b.cc.cd
database_url: sqlite:/data/db
ssh:
  enable: true
  listen: '[::]:2222'
  proxy_protocol: false
  external_port: null
  external_host: null
  host_key_verification: auto_reject
  inactivity_timeout: 5m
  keepalive_interval: 30s
http:
  listen: '[::]:8888'
  proxy_protocol: false
  external_port: 443
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
  trust_x_forwarded_headers: true
  session_max_age: 8h
  cookie_max_age: 1day
  sni_certificates: []
kubernetes:
  enable: false
  listen: '[::]:8443'
  proxy_protocol: false
  external_port: null
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
  session_max_age: 30m
mysql:
  enable: false
  listen: '[::]:33306'
  proxy_protocol: false
  external_port: null
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
  advertised_version: 8.0.3-Warpgate
postgres:
  enable: false
  listen: '[::]:55432'
  proxy_protocol: false
  external_port: null
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
vnc:
  enable: false
  listen: '[::]:5900'
  proxy_protocol: false
  external_port: null
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
  enable_ard_auth: false
rdp:
  enable: false
  listen: '[::]:3389'
  proxy_protocol: false
  external_port: null
  external_host: null
  certificate: /data/tls.certificate.pem
  key: /data/tls.key.pem
log:
  retention: 7days
  audit_retention: 11months 30days 3h 50m 24s
  send_to: null
  format: text
