[global]
   server role = standalone server
   workgroup = WORKGROUP
   server min protocol = SMB3_00
   server signing = mandatory
   disable netbios = yes
   smb ports = 445
   interfaces = lo 10.1.1.12
   bind interfaces only = yes
   map to guest = never
   username map = /etc/samba/user.map
   load printers = no
   printing = bsd
   printcap name = /dev/null

[AV]
   path = /srv/AV
   server smb encrypt = required
   browseable = yes
   read only = no
   guest ok = no
   valid users = iam.anuragvishwakarma
   create mask = 0660
   directory mask = 0770
