network:
  version: 2
  ethernets:
    eth0:
      match:
        macaddress: "bc:24:11:62:35:72"
      addresses:
      - "10.1.1.5/24"
      nameservers:
        addresses:
        - 10.1.1.2
        search:
        - l3b.cc.cd
      dhcp6: true
      dhcp6-overrides:
        use-dns: false
      ra-overrides:
        use-dns: false
      set-name: "eth0"
      routes:
      - to: "default"
        via: "10.1.1.1"
