apiVersion: v1
kind: Service
metadata:
  name: homepage
  annotations:
    lbipam.cilium.io/ips: {{ .Values.service.loadBalancerIP | quote }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: homepage
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
