server:
    local-zone: "l3b.cc.cd." transparent
    local-data: "dev.l3b.cc.cd. 30 IN A 10.1.1.5"
    local-data: "store.l3b.cc.cd. 30 IN A 10.1.1.12"
    local-data: "k8s.l3b.cc.cd. 30 IN A 10.1.1.200"
    local-data: "k8s-201.l3b.cc.cd. 30 IN A 10.1.1.201"
    local-data: "k8s-202.l3b.cc.cd. 30 IN A 10.1.1.202"
    local-data: "k8s-203.l3b.cc.cd. 30 IN A 10.1.1.203"
