server:
    interface: 127.0.0.1
    port: 5335
    access-control: 127.0.0.0/8 allow
    num-threads: 2
    so-reuseport: yes
    msg-cache-size: 32m
    rrset-cache-size: 64m
    cache-min-ttl: 0
    cache-max-ttl: 86400
    prefetch: yes
    serve-expired: no
    qname-minimisation: yes
    hide-identity: yes
    hide-version: yes
